
version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: brand-crud
        container_name: brand-crud
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: brand-crud
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

    db:
        image: mysql:8.4
        container_name: brand-crud-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "13306:3306"
        environment:
            MYSQL_DATABASE: crud
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network

    # Nginx Service
    web:
        image: 'nginx:alpine'
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
        driver: local
